var strVar = "";
strVar += "<!-- THIS WILL BE WRAPPED IN A <article> TAG -->";
strVar += "<!-- THIS WILL BE CREATED FOR EVRY TODO COLUMN -->";
strVar += "<header class=\"listHeader\">";
strVar += "    <div class=\"listTextBox\">";
strVar += "        <%= config.header %>";
strVar += "    <\/div>";
strVar += "    <div class=\"countBox\">";
strVar += "        <!--  <p class=\"totalText\">Total<\/p> -->";
strVar += "        <div>";
strVar += "            <p id=\"todoCount\">";
strVar += "                0";
strVar += "            <\/p>";
strVar += "            <p>projects<\/p>";
strVar += "        <\/div>";
strVar += "    <\/div>";
strVar += "    <div style=\"clear: both;\"><\/div>";
strVar += "<\/header>";
strVar += "<ul id=\"<%=config.type%>List\">";
strVar += "   ";
strVar += "<\/ul>";
module.exports = strVar;
