var strVar = "";
strVar += "   <div id=\"menubar\">";
strVar += "        <div id=\"menuCollection\">";
strVar += "            <div class=\"menu\">";
strVar += "                File";
strVar += "                <span class=\"menuItem import\">import<\/span>";
strVar += "                <span class=\"menuItem export\">export<\/span>";
strVar += "                <span class=\"menuItem contextClose\">exit<\/span>";
strVar += "            <\/div>";
strVar += "            <div class=\"menu\">";
strVar += "                View";
strVar += "                <span  class=\"menuItem contextMinimize\">minimize<\/span>";
strVar += "                <span  class=\"menuItem contextMaximize\">maximize<\/span>";
strVar += "                <span  class=\"menuItem fullscreen\">fullscreen<\/span>";
strVar += "            <\/div>";
strVar += "            <div class=\"menu\">";
strVar += "                Help";
strVar += "                <span class=\"menuItem import\">Dcumentation<\/span>";
strVar += "                <span class=\"menuItem import\">About<\/span>";
strVar += "            <\/div>";
strVar += "        <\/div>";
strVar += "        <div id=\"contextMenu\">";
strVar += "            <span class=\"contextItem contextMinimize\">-<\/span>";
strVar += "            <span class=\"contextItem contextMaximize\">[]<\/span>";
strVar += "            <span class=\"contextItem contextClose\">X<\/span>";
strVar += "        <\/div>";
strVar += "    <\/div>";

strVar += "<!-- THIS WILL BE WRAPPED IN A <header> ELEMENT -->";
strVar += "<!-- THIS WILL BE CREATED ONCE TO RENDER THE HEADER SECTION -->";
strVar += "<div id=\"resetTodo\">";
strVar += "    Reset";
strVar += "<\/div>";
strVar += "<div id=\"headerBar\">";
strVar += "    <div class=\"inputBox\">";
strVar += "        <input id=\"todoTextBox\" type=\"text\" placeholder=\"Add a thing to do\"><\/input>";
strVar += "        <span id=\"buttonAdd\" class=\"addButton\" todoid=\"todo-1449835803720-7\" position=\"3\">+<\/span>";
strVar += "    <\/div>";
strVar += "    <div class=\"totalBox\">";
strVar += "        <!-- <p class=\"totalText\"><\/p> -->";
strVar += "        <div>";
strVar += "            Total";
strVar += "            <p id=\"totalTodo\">";
strVar += "                0";
strVar += "            <\/p>";
strVar += "            <p>projects<\/p>";
strVar += "        <\/div>";
strVar += "    <\/div>";
strVar += "    <div style=\"clear: both;\"><\/div>";
strVar += "<\/div>";

module.exports = strVar;
